nome = input('Qual é o seu nome: ')
# print("Seja bem vindo {:^20}".format(nome))
# print("Seja bem vindo {:>20}".format(nome))
# print("Seja bem vindo {:<20}".format(nome)
print("Seja bem vindo {:=^20}".format(nome))
